version: '3'
services:

  frontend:
    container_name: frontend
    build:
      context: ./mltrace/server/ui
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: always
    networks:
      services-network:
        aliases:
          - frontend

  database:
    image: postgres
    volumes:      
       - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: sqlalchemy
    ports:
      - "5432:5432"
    restart: always
    networks:
      services-network:
        aliases:
          - database

  api:
    build:
      context: .
      dockerfile: ./mltrace/server/Dockerfile
    environment:
      PYTHONPATH: /src
      DB_URI: "postgresql://admin:admin@database:5432/sqlalchemy"
    volumes:
      - .:/src
    ports:
      - "8000:8000"
    env_file:
      - ./.flaskenv
    restart: always
    depends_on:
      - database
    networks:
      services-network:
        aliases:
          - api

  redis-celery: 
    image: redis:latest
  
volumes:  
  postgres_data:

networks:
  services-network:
    name: services-network
    driver: bridge